enable_audio_bell no

font_size 20.0

scrollback_lines 10000

clipboard_control write-clipboard write-primary read-clipboard read-primary

disable_ligatures always

tab_bar_style       powerline
tab_powerline_style slanted

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KEY_MAPS
map ctrl+shift+enter new_window_with_cwd
# END_KEY_MAPS

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
