enable_audio_bell no

font_size 20.0

scrollback_lines 10000

background #1e1e1e
foreground #d4d4d4
cursor #aaaaaa
selection_background #444444

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

